/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.moi.dms.consumer.registration.model.impl;

import com.moi.dms.consumer.registration.model.ConsumerRegistration;
import com.moi.dms.consumer.registration.service.ConsumerRegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the ConsumerRegistration service. Represents a row in the &quot;dms_consumer_registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsumerRegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsumerRegistrationImpl
 * @see ConsumerRegistration
 * @generated
 */
public abstract class ConsumerRegistrationBaseImpl
	extends ConsumerRegistrationModelImpl implements ConsumerRegistration {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consumer registration model instance should use the <code>ConsumerRegistration</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ConsumerRegistrationLocalServiceUtil.addConsumerRegistration(this);
		}
		else {
			ConsumerRegistrationLocalServiceUtil.updateConsumerRegistration(
				this);
		}
	}

}