/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.moi.dms.delete.documents.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MOIDeleteDocuments service. Represents a row in the &quot;moi_deletedocuments&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.moi.dms.delete.documents.model.impl.MOIDeleteDocumentsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.moi.dms.delete.documents.model.impl.MOIDeleteDocumentsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MOIDeleteDocuments
 * @generated
 */
@ProviderType
public interface MOIDeleteDocumentsModel extends BaseModel<MOIDeleteDocuments> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a moi delete documents model instance should use the {@link MOIDeleteDocuments} interface instead.
	 */

	/**
	 * Returns the primary key of this moi delete documents.
	 *
	 * @return the primary key of this moi delete documents
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this moi delete documents.
	 *
	 * @param primaryKey the primary key of this moi delete documents
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this moi delete documents.
	 *
	 * @return the document ID of this moi delete documents
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this moi delete documents.
	 *
	 * @param documentId the document ID of this moi delete documents
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the file entry ID of this moi delete documents.
	 *
	 * @return the file entry ID of this moi delete documents
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this moi delete documents.
	 *
	 * @param fileEntryId the file entry ID of this moi delete documents
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the file entry name of this moi delete documents.
	 *
	 * @return the file entry name of this moi delete documents
	 */
	@AutoEscape
	public String getFileEntryName();

	/**
	 * Sets the file entry name of this moi delete documents.
	 *
	 * @param fileEntryName the file entry name of this moi delete documents
	 */
	public void setFileEntryName(String fileEntryName);

	/**
	 * Returns the consumer code of this moi delete documents.
	 *
	 * @return the consumer code of this moi delete documents
	 */
	@AutoEscape
	public String getConsumerCode();

	/**
	 * Sets the consumer code of this moi delete documents.
	 *
	 * @param consumerCode the consumer code of this moi delete documents
	 */
	public void setConsumerCode(String consumerCode);

	/**
	 * Returns the module type of this moi delete documents.
	 *
	 * @return the module type of this moi delete documents
	 */
	@AutoEscape
	public String getModuleType();

	/**
	 * Sets the module type of this moi delete documents.
	 *
	 * @param moduleType the module type of this moi delete documents
	 */
	public void setModuleType(String moduleType);

	/**
	 * Returns the uploaded by of this moi delete documents.
	 *
	 * @return the uploaded by of this moi delete documents
	 */
	@AutoEscape
	public String getUploadedBy();

	/**
	 * Sets the uploaded by of this moi delete documents.
	 *
	 * @param uploadedBy the uploaded by of this moi delete documents
	 */
	public void setUploadedBy(String uploadedBy);

	/**
	 * Returns the uploaded date of this moi delete documents.
	 *
	 * @return the uploaded date of this moi delete documents
	 */
	public Date getUploadedDate();

	/**
	 * Sets the uploaded date of this moi delete documents.
	 *
	 * @param uploadedDate the uploaded date of this moi delete documents
	 */
	public void setUploadedDate(Date uploadedDate);

	/**
	 * Returns the status of this moi delete documents.
	 *
	 * @return the status of this moi delete documents
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this moi delete documents.
	 *
	 * @param status the status of this moi delete documents
	 */
	public void setStatus(String status);

	/**
	 * Returns the comments of this moi delete documents.
	 *
	 * @return the comments of this moi delete documents
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this moi delete documents.
	 *
	 * @param comments the comments of this moi delete documents
	 */
	public void setComments(String comments);

	/**
	 * Returns the updated by of this moi delete documents.
	 *
	 * @return the updated by of this moi delete documents
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this moi delete documents.
	 *
	 * @param updatedBy the updated by of this moi delete documents
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this moi delete documents.
	 *
	 * @return the updated date of this moi delete documents
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this moi delete documents.
	 *
	 * @param updatedDate the updated date of this moi delete documents
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the pending identifiers of this moi delete documents.
	 *
	 * @return the pending identifiers of this moi delete documents
	 */
	@AutoEscape
	public String getPendingIdentifiers();

	/**
	 * Sets the pending identifiers of this moi delete documents.
	 *
	 * @param pendingIdentifiers the pending identifiers of this moi delete documents
	 */
	public void setPendingIdentifiers(String pendingIdentifiers);

}