/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.moi.dms.audit.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MOIAudit service. Represents a row in the &quot;moi_audit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.moi.dms.audit.model.impl.MOIAuditModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.moi.dms.audit.model.impl.MOIAuditImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MOIAudit
 * @generated
 */
@ProviderType
public interface MOIAuditModel extends BaseModel<MOIAudit> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a moi audit model instance should use the {@link MOIAudit} interface instead.
	 */

	/**
	 * Returns the primary key of this moi audit.
	 *
	 * @return the primary key of this moi audit
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this moi audit.
	 *
	 * @param primaryKey the primary key of this moi audit
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit ID of this moi audit.
	 *
	 * @return the audit ID of this moi audit
	 */
	public long getAuditId();

	/**
	 * Sets the audit ID of this moi audit.
	 *
	 * @param auditId the audit ID of this moi audit
	 */
	public void setAuditId(long auditId);

	/**
	 * Returns the action performed by of this moi audit.
	 *
	 * @return the action performed by of this moi audit
	 */
	@AutoEscape
	public String getActionPerformedBy();

	/**
	 * Sets the action performed by of this moi audit.
	 *
	 * @param actionPerformedBy the action performed by of this moi audit
	 */
	public void setActionPerformedBy(String actionPerformedBy);

	/**
	 * Returns the action performed date of this moi audit.
	 *
	 * @return the action performed date of this moi audit
	 */
	public Date getActionPerformedDate();

	/**
	 * Sets the action performed date of this moi audit.
	 *
	 * @param actionPerformedDate the action performed date of this moi audit
	 */
	public void setActionPerformedDate(Date actionPerformedDate);

	/**
	 * Returns the action status of this moi audit.
	 *
	 * @return the action status of this moi audit
	 */
	@AutoEscape
	public String getActionStatus();

	/**
	 * Sets the action status of this moi audit.
	 *
	 * @param actionStatus the action status of this moi audit
	 */
	public void setActionStatus(String actionStatus);

	/**
	 * Returns the action description of this moi audit.
	 *
	 * @return the action description of this moi audit
	 */
	@AutoEscape
	public String getActionDescription();

	/**
	 * Sets the action description of this moi audit.
	 *
	 * @param actionDescription the action description of this moi audit
	 */
	public void setActionDescription(String actionDescription);

	/**
	 * Returns the action consumer of this moi audit.
	 *
	 * @return the action consumer of this moi audit
	 */
	@AutoEscape
	public String getActionConsumer();

	/**
	 * Sets the action consumer of this moi audit.
	 *
	 * @param actionConsumer the action consumer of this moi audit
	 */
	public void setActionConsumer(String actionConsumer);

}