/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.moi.dms.trace.request.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MOITraceRequest service. Represents a row in the &quot;moi_tracerequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.moi.dms.trace.request.model.impl.MOITraceRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.moi.dms.trace.request.model.impl.MOITraceRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MOITraceRequest
 * @generated
 */
@ProviderType
public interface MOITraceRequestModel extends BaseModel<MOITraceRequest> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a moi trace request model instance should use the {@link MOITraceRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this moi trace request.
	 *
	 * @return the primary key of this moi trace request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this moi trace request.
	 *
	 * @param primaryKey the primary key of this moi trace request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the request ID of this moi trace request.
	 *
	 * @return the request ID of this moi trace request
	 */
	public long getRequestId();

	/**
	 * Sets the request ID of this moi trace request.
	 *
	 * @param requestId the request ID of this moi trace request
	 */
	public void setRequestId(long requestId);

	/**
	 * Returns the requested by of this moi trace request.
	 *
	 * @return the requested by of this moi trace request
	 */
	@AutoEscape
	public String getRequestedBy();

	/**
	 * Sets the requested by of this moi trace request.
	 *
	 * @param requestedBy the requested by of this moi trace request
	 */
	public void setRequestedBy(String requestedBy);

	/**
	 * Returns the request incoming date of this moi trace request.
	 *
	 * @return the request incoming date of this moi trace request
	 */
	public Date getRequestIncomingDate();

	/**
	 * Sets the request incoming date of this moi trace request.
	 *
	 * @param requestIncomingDate the request incoming date of this moi trace request
	 */
	public void setRequestIncomingDate(Date requestIncomingDate);

	/**
	 * Returns the requested consumer code of this moi trace request.
	 *
	 * @return the requested consumer code of this moi trace request
	 */
	@AutoEscape
	public String getRequestedConsumerCode();

	/**
	 * Sets the requested consumer code of this moi trace request.
	 *
	 * @param requestedConsumerCode the requested consumer code of this moi trace request
	 */
	public void setRequestedConsumerCode(String requestedConsumerCode);

	/**
	 * Returns the requested consumer name of this moi trace request.
	 *
	 * @return the requested consumer name of this moi trace request
	 */
	@AutoEscape
	public String getRequestedConsumerName();

	/**
	 * Sets the requested consumer name of this moi trace request.
	 *
	 * @param requestedConsumerName the requested consumer name of this moi trace request
	 */
	public void setRequestedConsumerName(String requestedConsumerName);

	/**
	 * Returns the requested operation of this moi trace request.
	 *
	 * @return the requested operation of this moi trace request
	 */
	@AutoEscape
	public String getRequestedOperation();

	/**
	 * Sets the requested operation of this moi trace request.
	 *
	 * @param requestedOperation the requested operation of this moi trace request
	 */
	public void setRequestedOperation(String requestedOperation);

	/**
	 * Returns the requested document type of this moi trace request.
	 *
	 * @return the requested document type of this moi trace request
	 */
	@AutoEscape
	public String getRequestedDocumentType();

	/**
	 * Sets the requested document type of this moi trace request.
	 *
	 * @param requestedDocumentType the requested document type of this moi trace request
	 */
	public void setRequestedDocumentType(String requestedDocumentType);

	/**
	 * Returns the request valid of this moi trace request.
	 *
	 * @return the request valid of this moi trace request
	 */
	public boolean getRequestValid();

	/**
	 * Returns <code>true</code> if this moi trace request is request valid.
	 *
	 * @return <code>true</code> if this moi trace request is request valid; <code>false</code> otherwise
	 */
	public boolean isRequestValid();

	/**
	 * Sets whether this moi trace request is request valid.
	 *
	 * @param requestValid the request valid of this moi trace request
	 */
	public void setRequestValid(boolean requestValid);

	/**
	 * Returns the request result of this moi trace request.
	 *
	 * @return the request result of this moi trace request
	 */
	@AutoEscape
	public String getRequestResult();

	/**
	 * Sets the request result of this moi trace request.
	 *
	 * @param requestResult the request result of this moi trace request
	 */
	public void setRequestResult(String requestResult);

	/**
	 * Returns the request result date of this moi trace request.
	 *
	 * @return the request result date of this moi trace request
	 */
	public Date getRequestResultDate();

	/**
	 * Sets the request result date of this moi trace request.
	 *
	 * @param requestResultDate the request result date of this moi trace request
	 */
	public void setRequestResultDate(Date requestResultDate);

	/**
	 * Returns the comment of this moi trace request.
	 *
	 * @return the comment of this moi trace request
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this moi trace request.
	 *
	 * @param comment the comment of this moi trace request
	 */
	public void setComment(String comment);

}