components:
  schemas:
    MosipAPIHandler:
      description: Represents Document handled for Mosip.
      properties:
        date:
          format: date-time
          type: string
        id:
          format: int64
          type: integer
        title:
          type: string
      type: object
    JiraAPIHandler:
      description: Represents an uploaded document.
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        mimeType:
          type: string
        folderName:
          type: string
      type: object
    DocumentResult:
      description: Represents an uploaded document.
      properties:
        traceId:
          format: int64
          type: integer
        result:
          type: string
        resultMessage:
          type: string
        resultFile:
          type: object
      type: object
info:
  description: ""
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "Appointments"
  version: v1.0
openapi: 3.0.1
paths:
  "/uploadDocument":
    post:
      operationId: uploadMosipDocument
      parameters:
        - in: query
          name: ModuleType
          schema:
            type: string
        - in: query
          name: ConsumerCode
          schema:
            type: string
        - in: query
          name: DocumentType
          schema:
            type: string
        - in: query
          name: IdentifierNumber
          schema:
            type: string
        - in: query
          name: Metadata
          schema:
            type: string
        - in: query
          name: PreviousModuleType
          schema:
            type: string
        - in: query
          name: PreviousIdentifier
          schema:
            type: string
      requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                document:
                                    $ref: "#/components/schemas/MosipAPIHandler"
                                file:
                                    format: binary
                                    type: string
                            type: object
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "Upload Mosip Documents"
      tags: ["MosipAPIHandler"]
  "/updateDocument":
    post:
      operationId: updateMosipDocument
      parameters:
        - in: query
          name: ModuleType
          schema:
            type: string
        - in: query
          name: ConsumerCode
          schema:
            type: string
        - in: query
          name: DocumentType
          schema:
            type: string
        - in: query
          name: IdentifierNumber
          schema:
            type: string
        - in: query
          name: Metadata
          schema:
            type: string
        - in: query
          name: PreviousModuleType
          schema:
            type: string
        - in: query
          name: PreviousIdentifier
          schema:
            type: string
      requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                document:
                                    $ref: "#/components/schemas/MosipAPIHandler"
                                file:
                                    format: binary
                                    type: string
                            type: object
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "Update MOSIP Documents"
      tags: ["MosipAPIHandler"]
  "/getDocument":
    post:
      operationId: getMosipDocument
      parameters:
        - in: query
          name: ModuleType
          schema:
            type: string
        - in: query
          name: ConsumerCode
          schema:
            type: string
        - in: query
          name: DocumentType
          schema:
            type: string
        - in: query
          name: Identifier
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "View MOSIP Documents"
      tags: ["MosipAPIHandler"]
  "/addIDCSNumber":
    post:
      operationId: addIDCSNumber
      parameters:
        - in: query
          name: RegistrationNumber
          schema:
            type: string
        - in: query
          name: IDCSNumber
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "Add IDCS Number"
      tags: ["MosipAPIHandler"]
  "/deleteDocument":
    post:
      operationId: deleteMosipDocument
      parameters:
        - in: query
          name: ModuleType
          schema:
            type: string
        - in: query
          name: ConsumerCode
          schema:
            type: string
      requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                document:
                                    $ref: "#/components/schemas/MosipAPIHandler"
                                file:
                                    format: binary
                                    type: string
                            type: object
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "Bulk Delete MOSIP Documents"
      tags: ["MosipAPIHandler"]
  "/uploadJiraDocument":
    post:
      operationId: uploadJiraDocument
      parameters:
        - in: query
          name: consumerCode
          schema:
            type: string
        - in: query
          name: ticketNumber
          schema:
            type: string
        - in: query
          name: documentTitle
          schema:
            type: string
        - in: query
          name: metadata
          schema:
            type: string
      requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                document:
                                    $ref: "#/components/schemas/JiraAPIHandler"
                                file:
                                    format: binary
                                    type: string
                            type: object
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/DocumentResult"
                type: array
          description: "Upload Jira Documents"
      tags: ["JiraAPIHandler"]
